[build]
  command = "npm ci && node patch-sourcemap.js && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"
  CI = "false"
  
[build.processing]
  skip_processing = false

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 