# Generated by Django 5.1.6 on 2025-04-18 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0005_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
