# Generated by Django 5.1.6 on 2025-04-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0007_document_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
    ]
